add solution for 10-websockets 01-chat
js-tasks-ru/nodejs-20200728_aafutin pull request #10
Opened 2021-03-08 15:51 UTC by aafutin

2021-03-08 15:51 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-03-11 09:29 UTC, tadjik1 commented on 10-websockets/01-chat/socket.js
> +    const session = await Session.findOne({token}).populate('user');
нужно обязательно добавить `try/catch`, иначе в случае ошибки этой операции весь процесс сервера упадёт

2021-03-11 09:29 UTC, tadjik1 commented on 10-websockets/01-chat/socket.js
> +      await Message.create({
и здесь тоже нужен try/catch

2021-03-11 09:30 UTC, tadjik1 requested changes
@aafutin в целом всё хорошо, осталось лишь добавить обработку ошибок в паре мест

2021-03-11 09:59 UTC, aafutin commented
добавил try catch

2021-03-12 08:23 UTC, tadjik1 approved these changes
отличное решение! 👍

2021-03-12 08:24 UTC, merged